baseURL = ''
languageCode = 'en-us'
title = 'CS2-Nades'
theme = 'hugo-book'

disablePathToLower = true

[params]
  BookTheme = 'dark'
  BookToC = true
  BookSection = "*"
  BookSearch = false
  BookComments = false

[markup.tableOfContents]
  startLevel = 2
  endLevel = 4
